### PR TITLE
Bugfix/2 sensor ids

### PR DESCRIPTION
**Pull request by dbarentine**
Proposed fix for #2. Formats the address for normal sensors using {id}_{code} and for the thermostat sensors s{thermostatId} so it's consistent with the Forecast and Weather node addresses.

Note: This will be a breaking change for existing users as all sensor nodes will end up with a new address. I didn't see any way to do a migration of the existing nodes but if there is let me know.

### CODE REVIEW

**Comment by jimboca** [comment]
I've made changes to support this on my jdev branch, the change was required in two places so this PR is no longer valid.  But, the problem is the current version of polyglot is broken and can't delete nodes, so everyone will end up with both the old and new nodes and they will have to delete them from the polyglot UI.  If you want to test you can grab my branch and test it?

**Comment by jimboca** [comment]
I just received my sensors and set one up, and see the address with your code suggestion it uses rs100_vrsp.  I'm thinking it should just use the code vrsp, then if the sensor is moved from one thermostat to another the node address will stay the same, just the parent will change?  What @dbarentine and @Einstein42 think?

So the address will be:
 Address scheme:
 Devices: n<profile>_t<thermostatId> e.g. n003_t511892759243
 Thermostat Sensor: n<profile>_s<thermostatId> e.g. n003_s511892759243
 Current Weather: n<profile>_w<thermostatId> e.g. n003_w511892759243
 Forecast Weather: n<profile>_f<thermostatId> e.g. n003_f511892759243
 Sensors: n<profile>_rs_<sensor code> e.g. n003_rs_r6dr

**Comment by Einstein42** [comment]
Makes sense. Sensor codes "should" be unique.

**Comment by jimboca** [comment]
This will be implemented in next release.

**Pull request closed without merging**
